name: Deploy

on:
  push:
    branches:
      - master

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source


jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v4

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Replace placeholders with secrets
        run: |
            sed -i "s|PLACEHOLDER_API_KEY|${{ secrets.API_KEY }}|g" .env

      # build the react app
      - name: Build
        run: npm run build

      - name: Verify build output
        run: ls -la dist 
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
          
      # deploy the react app to github pages
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
